### ISSUE TITLE
Sometimes attempts sending on closing socket

### ISSUE THREAD

**Issue by anderspitman** [baygeldin/ws-streamify#3]
Hi @baygeldin, I'm using ws-streamify in an app that's opening and closing a lot of ws connections. Sometimes node crashes with `Error: WebSocket is not open readystate 2 (CLOSING)`, referring to [this line](https://github.com/baygeldin/ws-streamify/blob/25aa8caa8525f32403132b738cdf887bb0e198df/src/index.js#L101). I can see that you're handling socket.onclose and emitting an event to stop the stream, but I think what's happening is that sometimes an additional write command is issued before the event is handled. I'm not certain though. I'm not even sure that should be possible. I was hoping you might have a better idea. Maybe I'm doing something wrong.

**Comment by baygeldin** [comment]
Hi! Your assumption seems correct — `ws` documentation mentions that `close` event is emitted once the connection is already closed. Either way, an additional guard won't hurt :) Released `0.1.4`.

**Comment by anderspitman** [comment]
Awesome, thanks!
