### ISSUE TITLE
Chrome performance

### ISSUE THREAD

**Issue by anderspitman** [baygeldin/ws-streamify#5]
@baygeldin do you use ws-streamify on Chrome at all for streaming large files out of the browser? It works great in Firefox but I'm getting terrible performance in Chrome. I believe it's an issue with Chrome's WebSocket implementation, but maybe it's something else on my system. It's definitely not a ws-streamify problem (even though ws-streamify does suffer from it), so feel free to close this. I was just curious if you've run into this.

For reference see:

https://stackoverflow.com/questions/53659786/why-does-this-file-streaming-snippet-work-in-firefox-but-not-chrome

https://bugs.chromium.org/p/chromium/issues/detail?id=913645#c1

**Comment by baygeldin** [comment]
Hi! To be honest, I've never used it to stream files **from** the browser, so I can't help here really. I would suggest trying a different version of Chrome and/or testing it in on a virtual machine.

**Comment by anderspitman** [comment]
Thanks @baygeldin. Just FYI the problem is with Chrome devtools. When it's open, apparently all websocket messages are copied for some purpose. Running with devtools closed solves the problem. You can see the bug above for more details.
